-- Supports the AI "Find Matching Candidates" flow
-- (CvAnalysisPrismaRepository.searchCandidatePool), the flagship in-progress
-- feature's core read query, which today sequential-scans `users` and does
-- an unindexed array-overlap filter on `cv_analyses.skills`.
--
-- IMPORTANT: this was generated by hand-picking the two CreateIndex
-- statements out of `prisma migrate diff`'s output and dropping the
-- DropIndex statements it also proposed for jobs_title_trgm_idx/
-- jobs_description_trgm_idx/companies_name_trgm_idx — those exist only as
-- raw SQL with no schema.prisma annotation (see
-- 20260911123000_job_company_search_trgm_index), so any schema-diff tool
-- always sees them as drift to be dropped. Same near-miss already
-- documented on that migration; do not let a future `prisma migrate dev`
-- apply those drops.
--
-- CreateIndex
-- roleRef.name is resolved via Role.name's unique index before this table
-- is touched, so CvAnalysisPrismaRepository.searchCandidatePool's
-- `roleRef: { name: 'CANDIDATE' }, status: 'ACTIVE'` filter is effectively
-- `roleId = ? AND status = ?` against the full users table.
CREATE INDEX "users_roleId_status_idx" ON "users"("roleId", "status");

-- CreateIndex
-- Backs the `hasSome` (array-overlap / `&&`) skills filter in the same
-- query. Default array GIN ops (no custom operator class, unlike the trgm
-- indexes above) — expressible directly in schema.prisma's DSL via
-- `@@index([skills], type: Gin)`, so this one IS tracked by Prisma's schema
-- diff going forward.
CREATE INDEX "cv_analyses_skills_idx" ON "cv_analyses" USING GIN ("skills");
